name: Create Pull Request
on:
  push:
    branches:
      - master
  issue_comment:
    types: [created]

# require public member
# private member is treated as CONTRIBUTOR
jobs:
  createPullRequest:
    if: |
      github.event_name == 'issue_comment' &&
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') &&
      startsWith(github.event.comment.body, '/create release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node_version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: yarn install
      - name: Git Identity
        run: |
          git config --global user.name 'azu'
          git config --global user.email 'azu@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Versionup commit
        run: |
          yarn run versionup --yes
      - name: Set current CHANGELOG to output
        id: changelog
        shell: bash
        run: |
          version=$(node -p 'require("./lerna.json").version')
          echo "::set-output name=version::${version}"

